repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
        args: ["--quiet"]
      - id: djlint-django
  - repo: local
    hooks:
      - id: prettier-eslint
        name: Prettier and ESLint
        entry: prettier-eslint --write --list-different
        language: node
        types_or: [javascript, css, markdown, yaml]
        additional_dependencies: ["prettier-eslint-cli@8.0.1"]
