default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --recursive
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --expand-star-imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black