version: '3.8'
services:
   web:
       build: .
       command: uwsgi /app/deployment/uwsgi/uwsgi.ini
       volumes:
         - static_volume:/app/data/static/
       expose:
           - 8000
       depends_on:
         - postgres
   postgres:
       image: postgres:14-alpine
       volumes:
           - postgres_data:/var/lib/postgresql/data/
       env_file:
          - .env
       healthcheck:
         test: [ "CMD-SHELL", "pg_isready" ]
         interval: 10s
         timeout: 5s
         retries: 5
   nginx:
     build: ./deployment/nginx
     volumes:
       - static_volume:/app/data/static/
     ports:
       - "80:80"
     depends_on:
       - web

volumes:
  postgres_data:
  static_volume:
