# Generated by Django 3.1.8 on 2021-04-14 19:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_firstlevelmenuitem_rootpage_secondlevelmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutesLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'minutes label',
                'verbose_name_plural': 'minutes labels',
            },
        ),
        migrations.CreateModel(
            name='TaggedMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='core.minutes')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.minuteslabel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='minutes',
            name='labels',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedMinutes', to='core.MinutesLabel', verbose_name='Tags'),
        ),
    ]
