# Generated by Django 4.0.7 on 2022-11-02 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myhpi.core.markdown.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_add_footer'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'Angel'), ('R', 'Regular')], default='R', max_length=1)),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherObtainPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
                ('body', myhpi.core.markdown.fields.CustomMarkdownField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vouchers.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
        migrations.CreateModel(
            name='VoucherAllocation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.event')),
                ('vouchers', models.ManyToManyField(to='vouchers.voucher')),
            ],
        ),
    ]
