# Generated by Django 4.0.7 on 2022-09-04 12:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpage',
            name='attachments',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='attachments',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtaildocs.document'),
        ),
    ]
