# Generated by Django 4.0.7 on 2022-09-15 19:43

from django.db import migrations, models
import myhpi.core.markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rootpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='guests',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='body',
            field=myhpi.core.markdown.fields.CustomMarkdownField(),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='text',
            field=myhpi.core.markdown.fields.CustomMarkdownField(),
        ),
    ]
