# Generated by Django 3.1.8 on 2021-04-10 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("core", "0003_auto_20210407_1744"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstLevelMenuItem",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RootPage",
            fields=[
                (
                    "informationpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.informationpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.informationpage",),
        ),
        migrations.CreateModel(
            name="SecondLevelMenuItem",
            fields=[
                (
                    "firstlevelmenuitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.firstlevelmenuitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.firstlevelmenuitem",),
        ),
    ]
