# Generated by Django 4.0.7 on 2022-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_minutes_guests_alter_informationpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minuteslabel",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
