# Generated by Django 4.0.7 on 2022-09-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_minuteslabel_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectMenuItem',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
                ('redirect_url', models.CharField(help_text='The URL that the user should redirected to when selecting this menu item', max_length=255, verbose_name='redirect URL')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
    ]
