# Generated by Django 3.1.8 on 2021-04-14 19:13

import modelcluster.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_auto_20210414_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minutes",
            name="participants",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
