# Generated by Django 4.0.7 on 2022-10-08 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_redirectmenuitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterBase",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
        migrations.CreateModel(
            name="FooterCategory",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
        migrations.AlterField(
            model_name="redirectmenuitem",
            name="redirect_url",
            field=models.CharField(
                help_text="The URL that the user should be redirected to when selecting this menu item",
                max_length=255,
                verbose_name="redirect URL",
            ),
        ),
    ]
