# Generated by Django 4.0.7 on 2022-09-30 12:17

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("core", "0005_redirectmenuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="attachments",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="wagtaildocs.document"
            ),
        ),
        migrations.AddField(
            model_name="minutes",
            name="attachments",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="wagtaildocs.document"
            ),
        ),
        migrations.AlterField(
            model_name="redirectmenuitem",
            name="redirect_url",
            field=models.CharField(
                help_text="The URL that the user should be redirected to when selecting this menu item",
                max_length=255,
                verbose_name="redirect URL",
            ),
        ),
    ]
