# Generated by Django 4.0.7 on 2022-10-23 16:52

from django.db import migrations, models

import myhpi.core.markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_informationpage_attachments_minutes_attachments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("column_1", myhpi.core.markdown.fields.CustomMarkdownField()),
                ("column_2", myhpi.core.markdown.fields.CustomMarkdownField()),
                ("column_3", myhpi.core.markdown.fields.CustomMarkdownField()),
                ("column_4", myhpi.core.markdown.fields.CustomMarkdownField()),
            ],
        ),
    ]
