# Generated by Django 4.0.7 on 2023-08-15 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_footer_column_1_alter_footer_column_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="column_4",
        ),
    ]
