# Generated by Django 3.1.8 on 2021-04-18 17:01

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_abbreviationexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='visible_for',
            field=modelcluster.fields.ParentalManyToManyField(related_name='visible_for', to='auth.Group'),
        ),
    ]
