# Generated by Django 4.0.7 on 2023-11-21 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


def create_user_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        UserProfile = apps.get_model("core", "UserProfile")
        display_name = user.first_name + " " + user.last_name
        UserProfile.objects.create(user=user, display_name=display_name)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_remove_footer_column_4"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="minutes",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author",
                to="core.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="minutes",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moderator",
                to="core.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="minutes",
            name="participants",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="minutes", to="core.userprofile"
            ),
        ),
        migrations.RunPython(create_user_profiles),
    ]
