# Generated by Django 3.1.8 on 2021-06-12 11:28

from django.conf import settings
from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_minutes_visible_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minutes",
            name="participants",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="minutes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
