# Generated by Django 4.2.9 on 2024-01-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_footer_column_4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minuteslabel",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
