# Generated by Django 4.2.9 on 2024-01-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_minuteslabel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="minutes",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
