# Generated by Django 3.1.13 on 2021-11-25 11:25

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0009_auto_20210612_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="visible_for",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="visible_informationpages", to="auth.Group"
            ),
        ),
        migrations.AddField(
            model_name="minuteslist",
            name="visible_for",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="visible_minuteslist", to="auth.Group"
            ),
        ),
        migrations.AlterField(
            model_name="minutes",
            name="visible_for",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="visible_minutes", to="auth.Group"
            ),
        ),
    ]
