# Generated by Django 4.0.4 on 2022-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20211125_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="author_visible",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
