# Generated by Django 4.0.4 on 2022-06-07 07:32

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models

import myhpi.wagtail_markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0012_basepage_remove_informationpage_page_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstLevelMenuItem",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
        migrations.CreateModel(
            name="InformationPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
                ("body", myhpi.wagtail_markdown.fields.MarkdownField()),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
        migrations.CreateModel(
            name="Minutes",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
                ("date", models.DateField()),
                ("text", myhpi.wagtail_markdown.fields.MarkdownField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="auth.group"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
        migrations.CreateModel(
            name="RootPage",
            fields=[
                (
                    "informationpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.informationpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.informationpage",),
        ),
        migrations.CreateModel(
            name="SecondLevelMenuItem",
            fields=[
                (
                    "firstlevelmenuitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.firstlevelmenuitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.firstlevelmenuitem",),
        ),
        migrations.CreateModel(
            name="TaggedMinutes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="core.minutes",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.minuteslabel"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinutesList",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="auth.group"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
        migrations.AddField(
            model_name="minutes",
            name="labels",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="core.TaggedMinutes",
                to="core.MinutesLabel",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="minutes",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minutes",
            name="participants",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="minutes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
