# Generated by Django 4.2.9 on 2024-04-06 17:18
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def replace_menu_items(apps, schema_editor):
    BasePage = apps.get_model("core", "BasePage")
    MenuItem = apps.get_model("core", "MenuItem")
    menu_item_content_type = ContentType.objects.get_for_model(MenuItem)
    FirstLevelMenuItem = apps.get_model("core", "FirstLevelMenuItem")
    SecondLevelMenuItem = apps.get_model("core", "SecondLevelMenuItem")
    Revisions = apps.get_model("wagtailcore", "Revision")

    first_level_menu_item_content_type_id = ContentType.objects.get_for_model(FirstLevelMenuItem).id
    second_level_menu_item_content_type_id = ContentType.objects.get_for_model(
        SecondLevelMenuItem
    ).id

    for menu_item in FirstLevelMenuItem.objects.all():
        basepage_ptr_id = menu_item.basepage_ptr_id
        menu_item.delete(keep_parents=True)
        basepage = BasePage.objects.get(pk=basepage_ptr_id)
        new_menu_item = MenuItem(basepage_ptr_id=basepage_ptr_id)
        new_menu_item.__dict__.update(basepage.__dict__)
        new_menu_item.content_type_id = menu_item_content_type
        new_menu_item.save()
    for menu_item in SecondLevelMenuItem.objects.all():
        basepage_ptr_id = menu_item.basepage_ptr_id
        menu_item.delete(keep_parents=True)
        basepage = BasePage.objects.get(pk=basepage_ptr_id)
        new_menu_item = MenuItem(basepage_ptr_id=basepage_ptr_id)
        new_menu_item.__dict__.update(basepage.__dict__)
        new_menu_item.content_type_id = menu_item_content_type
        new_menu_item.save()

    for revision in Revisions.objects.filter(content_type_id=first_level_menu_item_content_type_id):
        revision.content_type_id = menu_item_content_type
        revision.base_content_type_id = menu_item_content_type
        revision.save()
    for revision in Revisions.objects.filter(
        content_type_id=second_level_menu_item_content_type_id
    ):
        revision.content_type_id = menu_item_content_type
        revision.base_content_type_id = menu_item_content_type
        revision.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_menuitem"),
        ("wagtailcore", "0070_rename_pagerevision_revision"),
    ]

    operations = [
        migrations.RunPython(replace_menu_items),
    ]
