# Generated by Django 5.0.8 on 2024-11-22 14:42

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_abbreviationexplanation_locale_and_more"),
    ]

    operations = [
        BootstrapTranslatableModel("core.AbbreviationExplanation"),
    ]
