# Generated by Django 4.2.9 on 2024-04-06 17:18
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def replace_menu_items(apps, schema_editor):
    MenuItem = apps.get_model("core", "MenuItem")
    menu_item_content_type = ContentType.objects.get_for_model(MenuItem)
    FirstLevelMenuItem = apps.get_model("core", "FirstLevelMenuItem")
    SecondLevelMenuItem = apps.get_model("core", "SecondLevelMenuItem")
    for menu_item in FirstLevelMenuItem.objects.values():
        FirstLevelMenuItem.objects.get(id=menu_item["id"]).delete()
        menu_item["content_type_id"] = menu_item_content_type.id
        MenuItem.objects.create(**menu_item)
    for menu_item in SecondLevelMenuItem.objects.values():
        SecondLevelMenuItem.objects.get(id=menu_item["id"]).delete()
        menu_item["content_type_id"] = menu_item_content_type.id
        MenuItem.objects.create(**menu_item)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_menuitem"),
    ]

    operations = [
        migrations.RunPython(replace_menu_items),
    ]
