# Generated by Django 4.0.4 on 2022-06-07 12:11

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0013_firstlevelmenuitem_informationpage_minutes_rootpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepage",
            name="visible_for",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="visible_basepages", to="auth.group"
            ),
        ),
    ]
