# Generated by Django 4.2.9 on 2024-04-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_merge_first_and_second_level_menu_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secondlevelmenuitem",
            name="firstlevelmenuitem_ptr",
        ),
        migrations.DeleteModel(
            name="FirstLevelMenuItem",
        ),
        migrations.DeleteModel(
            name="SecondLevelMenuItem",
        ),
    ]
