# Generated by Django 4.0.4 on 2022-06-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_basepage_visible_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="author_visible",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
