# Generated by Django 4.0.4 on 2022-07-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_informationpage_author_visible"),
        ("core", "0015_informationpage_author_visible"),
    ]

    operations = []
