# Generated by Django 4.0.4 on 2022-07-08 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0016_merge_20220705_2034"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="minutes",
            name="group",
        ),
        migrations.AlterField(
            model_name="minutes",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="minutes",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moderator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
