# Generated by Django 3.1.8 on 2021-06-12 10:17

from django.db import migrations, models
import myhpi.wagtail_markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=myhpi.wagtail_markdown.fields.MarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='text',
            field=models.CharField(max_length=254),
        ),
    ]
