# Generated by Django 3.1.8 on 2021-06-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='description',
        ),
    ]
