# Generated by Django 3.1.8 on 2021-06-12 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("polls", "0007_auto_20210612_1620"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollList",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.basepage",),
        ),
    ]
