# Generated by Django 4.0.7 on 2022-09-15 19:17

from django.db import migrations

import myhpi.core.markdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_polllist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=myhpi.core.markdown.fields.CustomMarkdownField(),
        ),
    ]
