# Generated by Django 4.0.7 on 2023-12-20 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import myhpi.core.markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_footer_column_4'),
        ('polls', '0009_alter_poll_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
                ('description', myhpi.core.markdown.fields.CustomMarkdownField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('results_visible', models.BooleanField(default=False)),
                ('already_voted', models.ManyToManyField(related_name='elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
        migrations.CreateModel(
            name='ElectionBallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', myhpi.core.markdown.fields.CustomMarkdownField()),
                ('election', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='polls.election')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionBallotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.electionballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.electioncandidate')),
            ],
            options={
                'unique_together': {('ballot', 'candidate', 'rank')},
            },
        ),
        migrations.AddField(
            model_name='electionballot',
            name='entries',
            field=models.ManyToManyField(through='polls.ElectionBallotEntry', to='polls.electioncandidate'),
        ),
    ]
