# Generated by Django 4.0.7 on 2024-01-25 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0009_alter_poll_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='page',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollChoice',
        ),
    ]
