# Generated by Django 4.0.7 on 2023-12-20 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_election_electionballot_electioncandidate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollChoice',
            new_name='MajorityVoteChoice',
        ),
        migrations.RemoveField(
            model_name='election',
            name='already_voted',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='participants',
        ),
        migrations.AddField(
            model_name='poll',
            name='already_voted',
            field=models.ManyToManyField(related_name='base_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
