# Generated by Django 4.0.7 on 2024-01-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import myhpi.core.markdown.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_footer_column_4'),
        ('polls', '0010_remove_pollchoice_page_delete_poll_delete_pollchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePoll',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
                ('description', myhpi.core.markdown.fields.CustomMarkdownField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('results_visible', models.BooleanField(default=False)),
                ('already_voted', models.ManyToManyField(related_name='base_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
        migrations.CreateModel(
            name='RankedChoiceBallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RankedChoiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', myhpi.core.markdown.fields.CustomMarkdownField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajorityVotePoll',
            fields=[
                ('basepoll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.basepoll')),
                ('question', models.CharField(max_length=254)),
                ('max_allowed_answers', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.basepoll',),
        ),
        migrations.CreateModel(
            name='RankedChoicePoll',
            fields=[
                ('basepoll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.basepoll')),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.basepoll',),
        ),
        migrations.CreateModel(
            name='RankedChoiceBallotEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.rankedchoiceballot')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.rankedchoiceoption')),
            ],
            options={
                'unique_together': {('ballot', 'option', 'rank')},
            },
        ),
        migrations.AddField(
            model_name='rankedchoiceballot',
            name='entries',
            field=models.ManyToManyField(through='polls.RankedChoiceBallotEntry', to='polls.rankedchoiceoption'),
        ),
        migrations.AddField(
            model_name='rankedchoiceoption',
            name='poll',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.rankedchoicepoll'),
        ),
        migrations.CreateModel(
            name='MajorityVoteChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=254)),
                ('votes', models.IntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.majorityvotepoll')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
