# Generated by Django 4.0.7 on 2023-12-20 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_remove_footer_column_4'),
        ('polls', '0011_rename_pollchoice_majorityvotechoice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='MajorityVote',
        ),
    ]
