# Generated by Django 5.0.8 on 2025-07-23 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_basepoll_rankedchoiceballot_rankedchoiceoption_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="majorityvotechoice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rankedchoiceoption",
            options={},
        ),
        migrations.AddField(
            model_name="majorityvotechoice",
            name="translation_key",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name="majorityvotechoice",
            name="locale",
            field=models.ForeignKey(
                null=True,
                editable=False,
                to="wagtailcore.locale",
                on_delete=models.CASCADE,
            ),
        ),
        migrations.AddField(
            model_name="rankedchoiceoption",
            name="translation_key",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name="rankedchoiceoption",
            name="locale",
            field=models.ForeignKey(
                null=True,
                editable=False,
                to="wagtailcore.locale",
                on_delete=models.CASCADE,
            ),
        ),
        # Remove unique_together for now, will add in a later migration
    ]
