name: dependabot-assign
on:
  pull_request:
    types: [opened]
jobs:
  assign:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1
        with:
          reviewers: Paula-Kli